version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment: 
      
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
