version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123.AbcD
    ports: 
      - "1433:1433"          
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    
